# Используем образ Nginx в качестве базового
   FROM nginx:alpine

   # Копируем файлы из текущей директории в директорию /usr/share/nginx/html
   COPY . /usr/share/nginx/html

   # Указываем, что Nginx будет слушать на 80 порту
   EXPOSE 80
